### ISSUE TITLE
Documenta los parámetros

### ISSUE THREAD

**Issue by lmagarin** [JavierSA-dev/javaDocAlmacen#2]
https://github.com/JavierSA-dev/javaDocAlmacen/blob/b3da31822e410faa524663e51470ded4c3e0650d/src/almacen/Almacen.java#L110

**Comment by JavierSA-dev** [comment]
He añadido los comentarios

**Comment by lmagarin** [comment]
Hola @JavierSA-dev 
El problema es que en este commit que me indicas no hay cambios, por lo que no veo los comentarios añadidos. El cerrar el issue en el commit es para ver EXÁCTAMENTE  el issue solucionado
@andresfp16

**Comment by lmagarin** [comment]
Pero lo has hecho en el de antes!!!! 😮 
Menudo follón.
